name: Build (Windows)

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*'

jobs:
  run_tests:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Project
        working-directory: ${{github.workspace}}
        run: python ${{github.workspace}}\configure.py -G "Visual Studio 17 2022" -- -DJAMBA_DOWNLOAD_VSTSDK=ON -A x64

      - name: Run test/validate/archive (Release)
        working-directory: ${{github.workspace}}/build
        run: .\jamba.bat --release -b test validate archive

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: archive-windows
          path: ${{github.workspace}}/build/*.zip
